
spring:
  :datasource:
  datasource:
    url: jdbc:mysql://47.95.248.109:3306/scan?serverTimezone=GMT%2B8
    username: aliyun
    password: aliyun
    driver-class-name: com.mysql.cj.jdbc.NonRegisteringDriver
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: utf-8
    servlet:
      content-type: text/html

mybatis:
  type-aliases-package: com.neo.scan.model
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8090
